name: Build and push to ECR

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}           #github-actions-deploy-role
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          docker build -t $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG ./app/services/frontend
          docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Generate kubeconfig                     # you do need a kubeconfig file to interact with the cluster after it exists.
        run: |
          mkdir -p "$GITHUB_WORKSPACE/.kube"
          aws eks update-kubeconfig \
            --name "${{ secrets.CLUSTER_NAME }}" \
            --region "${{ secrets.AWS_REGION }}" \
            --kubeconfig "$GITHUB_WORKSPACE/.kube/config"

          echo "KUBECONFIG=$GITHUB_WORKSPACE/.kube/config" >> $GITHUB_ENV

      - name: Update deployment image   # Updates the Kubernetes deployment YAML to use the newly built image.
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${GITHUB_SHA::8}
        run: |
          IMAGE_URI=${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
          sed -i "s|IMAGE_PLACEHOLDER|$IMAGE_URI|g" ./app/k8s/deployment.yaml

      - name: Deploy to EKS
        run: |
          kubectl apply -f ./app/k8s/deployment.yaml
          kubectl apply -f ./app/k8s/service.yml
